### ISSUE TITLE
ModuleNotFoundError: No module named 'django.utils.six'

### ISSUE THREAD

**Issue by shahabaz** [djaodjin/djaodjin-saas#234]
I am using python 3.6.5 and Django 3.0.5 while trying to migrate the db I got this error.

warning: config file F:\SAAS\djaodjin-saas\credentials does not exist.
Use Django templates engine.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "F:\SAAS\venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "F:\SAAS\venv\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "F:\SAAS\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "F:\SAAS\venv\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "F:\SAAS\venv\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "F:\SAAS\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\SAAS\djaodjin-saas\saas\models.py", line 76, in <module>
    from django.utils.six import python_2_unicode_compatible
ModuleNotFoundError: No module named 'django.utils.six'

**Comment by smirolo** [comment]
Sorry I forgot to write an update on this issue. The last commit related to Django3.0 support is commit 11a3cf9f. Since then, the tests are run - and pass so far :) - with the following combinations:

- **Python:** 2.7, **Django:** 1.11, **Django Rest Framework:** 3.9.4
- **Python:** 3.6, **Django:** 2.2 ([LTS](https://www.djangoproject.com/download/)), **Django Rest Framework:** 3.11
- **Python:** 3.6, **Django:** 3.0 (latest), **Django Rest Framework:** 3.11

See also #233
