### ISSUE TITLE
followed the install steps, ModuleNotFoundError: No module named 'signup'

### ISSUE THREAD

**Issue by j2l** [djaodjin/djaodjin-saas#304]
Hello and thank you for sharing this!
Install went great.
But when adding dummy data using `python ./manage.py load_test_transactions`, I got:
```
config loaded from /home/pm/Documents/github/djaodjin-saas-master/credentials
Use Django templates engine.
Traceback (most recent call last):
  File "/home/pm/Documents/github/djaodjin-saas-master/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pm/Documents/github/djaodjin-saas-master/.djaovenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/pm/Documents/github/djaodjin-saas-master/.djaovenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pm/Documents/github/djaodjin-saas-master/.djaovenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 257, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/pm/Documents/github/djaodjin-saas-master/.djaovenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pm/Documents/github/djaodjin-saas-master/testsite/management/commands/load_test_transactions.py", line 20, in <module>
    from signup.helpers import full_name_natural_split
ModuleNotFoundError: No module named 'signup'
```

It looks like it uses my python 3.10 instead of the venv.
Maybe it should be fixed when using the Django 4.2 version. But how to do it?
Any idea how to fix it?

Thank you again!

**Comment by smirolo** [comment]
Trying to eagerly to keep the same tests to run on this app and the full-fledged project, while  making as much dependencies as possible optional. The previous two commits fix the issue.

Thank you!

**Comment by j2l** [comment]
Thank you!
